name: project_coconut
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  image_picker: ^1.1.2
  path: ^1.9.1
  equatable: ^2.0.7

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
